apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: simpleapp
build:
  artifacts:
    - image: simpleapp
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      ignoreChanges: true
  local:
    push: false
deploy:
  kustomize: {}
  statusCheckDeadlineSeconds: 240
profiles:
  - name: push
    build:
      local:
        push: true
  - name: dev
    deploy:
      kustomize:
        buildArgs:
          - '--enable-alpha-plugins'
        paths:
          - deployment-configuration/profiles/dev
  - name: prod
    deploy:
      kustomize:
        buildArgs:
          - '--enable-alpha-plugins'
        paths:
          - deployment-configuration/profiles/prod
