apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  selector:
    matchLabels:
      service: simpleapp
  template:
    metadata:
      labels:
        service: simpleapp
    spec:
      containers:
      - image: simpleapp
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: simpleapp
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        envFrom:
        - configMapRef:
            name: simpleapp
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  service: simpleapp
              topologyKey: "kubernetes.io/hostname"
