apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: simpleapp
        resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
      - name: dockerlogin
